Tag 34
Clanhouse/tagster pull request #10
Opened 2021-07-20 18:14 UTC by flapek

Backend solution refactor and add test projects to it.

2021-07-20 21:46 UTC, msdfib requested changes

2021-07-21 16:22 UTC, flapek commented on TagsterWebAPI/tests/Tagster.Application.UnitTests/UnitTest1.cs
> +    public class UnitTest1
But you can't do E2E test using only backend application. E2E test we can make if we connect our Chrome extension and service. Unit tests and integration test can cover all business requirements.

2021-07-21 16:24 UTC, flapek commented on TagsterWebAPI/tests/Tagster.Domain.UnitTests/UnitTest1.cs
> +    public class UnitTest1
It's redundant class because I make test for all normal project. And this is only a dummy test. If we have something to testing we remove this.

2021-07-21 16:41 UTC, flapek commented on TagsterWebAPI/src/TagsterWebAPI/Controllers/TagsController.cs
> +        public TagsController(ITagsterDbContext tagsterDb)
I move context to service class

2021-07-21 19:58 UTC, msdfib approved these changes

2021-07-21 20:12 UTC, merged