JWT created. Authentication generates token.
Clanhouse/tagster pull request #13
Opened 2021-08-24 09:22 UTC by KedarSki

2021-08-31 20:28 UTC, flapek requested changes

2021-08-31 20:28 UTC, flapek commented on TagsterWebAPI/src/TagsterWebAPI/Controllers/AuthenticateController.cs
> +        }
make from this one constructor

2021-09-06 19:47 UTC, kacperantoniak commented on README.md
> +Tagsster is a backend and frontend application that allows you to add tags to browsed profiles on [LinkedIn](https://www.linkedin.com).
"Tagster" instead of "Tagsster"

2021-09-09 17:14 UTC, kacperantoniak approved these changes

2021-09-09 17:20 UTC, orzeech approved these changes

2021-09-09 17:20 UTC, orzeech commented on TagsterWebAPI/libraries/Tagster.Auth/Factory/TokenValidationFactory.cs
> +                    Console.WriteLine($"Loaded X.509 certificate from location: '{options.Certificate.Location}' {keyType}.");
Here and in other places I'd use some kind of a configurable log provider. If yuo don't want to do it in the scope of this task, create a new one

2021-09-09 17:20 UTC, orzeech commented on TagsterWebAPI/libraries/Tagster.Auth/Services/IIdentityService.cs
> +        //Task<UserDto> GetAsync(Guid id, CancellationToken cancellationToken);
do not commit commented-out code

2021-09-09 17:20 UTC, orzeech commented on TagsterWebAPI/libraries/Tagster.DataAccess/Migrations/20210905081434_Initial.Designer.cs
> +>>>>>>> e56f5e008b44f871bf3346eb31d0999174b491f7:TagsterWebAPI/libraries/Tagster.DataAccess/Migrations/20210906183605_Initial.Designer.cs
isn't something wrong with these?

2021-09-10 06:05 UTC, flapek approved these changes

2021-09-11 12:09 UTC, merged